import type { Perfume } from './types';

export const perfumes: Perfume[] = [
  {
    id: 'p001',
    name: 'Esencia Etérea',
    brand: 'Aura Fragrances',
    price: 180,
    stock: 25,
    imageUrl: 'https://picsum.photos/seed/p001/600/600',
    description: 'Una fragancia ligera y aireada con notas de salida de bergamota y un corazón de jazmín y rosa, sobre una base de sándalo y almizcle. Perfecta para una elegancia diaria.',
    category: 'Para Ella',
    notes: ['bergamota', 'jazmín', 'rosa', 'sándalo', 'almizcle'],
  },
  {
    id: 'p002',
    name: 'Noir Nuit',
    brand: 'Shadow Scents',
    price: 220,
    stock: 15,
    imageUrl: 'https://picsum.photos/seed/p002/600/600',
    description: 'Una fragancia audaz y misteriosa para el hombre moderno. Presenta notas especiadas de pimienta negra y cardamomo, un corazón de cuero y una base profunda de oud y ámbar.',
    category: 'Para Él',
    notes: ['pimienta negra', 'cardamomo', 'cuero', 'oud', 'ámbar'],
  },
  {
    id: 'p003',
    name: 'Solaris',
    brand: 'Equinox Perfumes',
    price: 195,
    stock: 30,
    imageUrl: 'https://picsum.photos/seed/p003/600/600',
    description: 'Una fragancia vibrante y unisex que captura la calidez del sol. Notas de salida cítricas de pomelo y mandarina se mezclan con un corazón floral y una base de vetiver.',
    category: 'Unisex',
    notes: ['pomelo', 'mandarina', 'neroli', 'vetiver'],
  },
  {
    id: 'p004',
    name: 'Verbena Oceánica',
    brand: 'Coastal Aromas',
    price: 165,
    stock: 40,
    imageUrl: 'https://picsum.photos/seed/p004/600/600',
    description: 'Una fragancia refrescante y vigorizante que recuerda a la brisa marina. Notas frescas de verbena y sal marina se complementan con toques de madera de cedro y salvia.',
    category: 'Unisex',
    notes: ['verbena', 'sal marina', 'madera de cedro', 'salvia'],
  },
    {
    id: 'p005',
    name: 'Pétalo de Terciopelo',
    brand: 'Aura Fragrances',
    price: 250,
    stock: 18,
    imageUrl: 'https://picsum.photos/seed/p005/600/600',
    description: 'Una lujosa y romántica fragancia floral. Un ramo de peonía, rosa y fresia con un suave acabado empolvado de madera de cachemira.',
    category: 'Para Ella',
    notes: ['peonía', 'rosa', 'fresia', 'madera de cachemira'],
  },
  {
    id: 'p006',
    name: 'Terra Firma',
    brand: 'Shadow Scents',
    price: 210,
    stock: 22,
    imageUrl: 'https://picsum.photos/seed/p006/600/600',
    description: 'Una fragancia terrosa y robusta para hombres. Una potente mezcla de hoja de tabaco, café rico y canela especiada con una base ahumada de incienso.',
    category: 'Para Él',
    notes: ['hoja de tabaco', 'café', 'canela', 'incienso'],
  },
  {
    id: 'p007',
    name: 'Flor de Luna',
    brand: 'Equinox Perfumes',
    price: 200,
    stock: 28,
    imageUrl: 'https://picsum.photos/seed/p007/600/600',
    description: 'Una fragancia encantadora que florece a la luz de la luna. Presenta jazmín de noche, nardo y un toque de vainilla para un aroma cautivador.',
    category: 'Para Ella',
    notes: ['jazmín de noche', 'nardo', 'vainilla', 'ylang-ylang'],
  },
  {
    id: 'p008',
    name: 'Apex',
    brand: 'Coastal Aromas',
    price: 230,
    stock: 12,
    imageUrl: 'https://picsum.photos/seed/p008/600/600',
    description: 'Una fragancia para el máximo rendimiento. Una presencia imponente con notas de piña, abedul y grosella negra, que finaliza con una base segura de almizcle y musgo de roble.',
    category: 'Para Él',
    notes: ['piña', 'abedul', 'almizcle', 'musgo de roble'],
  },
];
